### PR TITLE
feat: Fibocom FM350-GL Initial support

### PR DESCRIPTION
**Pull request by prusa-dev**
## Initial Fibocom FM350-GL support

- LTE Metrics
- 5G Metrics

3ginfo-lite-fm350

### CODE REVIEW

**Comment by prusa-dev** [comment]
## Responses from modem:

### My response
```
AT+COPS=3,2;+COPS?
+COPS:0,2,"25001",7

OK
AT+CEREG=2;+CEREG?
+CEREG: 2,1,"1234","00123456",7

OK
AT+CGREG=2;+CGREG?;+CSQ
+CGREG: 2,1,"1234","00123456",7,"FF"

+CSQ: 9, 99

OK
AT+GTCCINFO?;+GTCAINFO?
+GTCCINFO:
1,4,250,1,1234,000123456,1802,470,103,100,-4,39,39,7

+GTCAINFO:
PCC:103,470,1802,100,100,1,1,2,2,-102
SCC 1:2,0,138,18,38100,100,255,0,255,0,255,-102


OK
AT+GTSENRDTEMP=1
+GTSENRDTEMP: 1,37628

OK
AT+GTPKGVER?;+CGMI?;+CGMM?;+CGMR?;+CIMI?;+ICCID;+CGSN?
+GTPKGVER: "81600.0000.00.29.22.40_5000.0000.050.000.046_E41"

+CGMI: "Fibocom Wireless Inc."

+CGMM: "FM350-GL"

+CGMR: "81600.0000.00.29.22.40"

+CIMI: "250015499041814"

+ICCID: 89701010054990418149

+CGSN: "354174400124199"

OK
```
### Other response 1:
```
AT+COPS?
+COPS:0,2,"25001",13

OK
AT+GTCCINFO?;+GTCAINFO?
+GTCCINFO:
1,4,250,1,1234,001234567,1721,223,103,50,6,62,62,18
1,9,,,FFFFFFF,00FFFFFFF,723322,143,5079,500,13,68,68,80
2,4,,,FFFF,00FFFFFFF,1721,160,,53,53,0

+GTCAINFO:
PCC:5079,143,723322,500,500,3,1,1,4,-86
PCC:103,223,1721,50,50,2,1,3,3,-78
SCC 1:2,0,101,296,350,50,255,2,255,2,255,-78


OK
```
### Other response 2:
```
AT+COPS?
+COPS:0,2,"46015",11

OK
AT+GTCCINFO?;+GTCAINFO?
+GTCCINFO:
1,9,460,0,123456,123456789,504990,482,5041,25,6,63,63,86
2,9,,,FFFFFFF,00FFFFFFF,504990,480,,60,60,72
2,9,,,FFFFFFF,00FFFFFFF,504990,376,,55,55,62
2,9,,,FFFFFFF,00FFFFFFF,504990,111,,51,51,58


+GTCAINFO:
PCC:5041,482,504990,0,2,1,5,5
SCC1:2,1,,480,504990,0,0,,,5,5,0,60,72


OK
```

**Comment by 4IceG** [comment]
@prusa-dev If you can, improve/adjust PR to make it compatible with other 3ginfo-lite modem scripts, e.g.
- Protocol names in lower case (ncm..)
- MODE for MODE_NUM 13) MODE="5G NSA |" or MODE="LTE |" or MODE="LTE-A |" to avoid writing with the sign '+' (MODE="LTE-A + 5G |")

**Comment by prusa-dev** [comment]
@4IceG 
The modem in 5G NSA mode responds:
```
+GTCCINFO:
1,4,250,1,1234,001234567,1721,223,103,50,6,62,62,18
1,9,,,FFFFFFF,00FFFFFFF,723322,143,5079,500,13,68,68,80
2,4,,,FFFF,00FFFFFFF,1721,160,,53,53,0

+GTCAINFO:
PCC:5079,143,723322,500,500,3,1,1,4,-86
PCC:103,223,1721,50,50,2,1,3,3,-78
SCC 1:2,0,101,296,350,50,255,2,255,2,255,-78
```

As you can see, there is 2 `PCC` in response. How it should be shown?
In current version i did this:
image

**Comment by 4IceG** [comment]
> @4IceG The modem in 5G NSA mode responds:
> 
> ```
> +GTCCINFO:
> 1,4,250,1,1234,001234567,1721,223,103,50,6,62,62,18
> 1,9,,,FFFFFFF,00FFFFFFF,723322,143,5079,500,13,68,68,80
> 2,4,,,FFFF,00FFFFFFF,1721,160,,53,53,0
> 
> +GTCAINFO:
> PCC:5079,143,723322,500,500,3,1,1,4,-86
> PCC:103,223,1721,50,50,2,1,3,3,-78
> SCC 1:2,0,101,296,350,50,255,2,255,2,255,-78
> ```
> 
> As you can see, there is 2 `PCC` in response. How it should be shown?

This section Primary band (PCC) | PCI & EARFCN should look a little different (it doesn't show what it should).

We need to take one PCC as primary/main and add the rest to it (then it looks logical).

Now I don't have a PDF open for this modem, so I don't see how they explained it, but it would be good to stick to this form.
`5G NSA | B7 (2600 MHz) + B1 (2100 MHz) / n78 (3500 MHz)`

Depending on what it looks like in the output of the at command, but to keep PCC + SCC1 / SCC2 and not PCC + SCC1 / PCC + SCC1 + SCC2

**Comment by prusa-dev** [comment]
> This section Primary band (PCC) | PCI & EARFCN should look a little different (it doesn't show what it should).
> 
> We need to take one PCC as primary/main and add the rest to it (then it looks logical).

I understand that this section is supposed to show information about the PCC as primary/main, but the modem in 5G NSA mode connects to both 4G and 5G, so the GTCAINFO command response contains two PCC values one for 4G and one for 5G. If `Primary band (PCC) | PCI & EARFCN` section should only display one value, where should the second value be displayed?


> Now I don't have a PDF open for this modem, so I don't see how they explained it, but it would be good to stick to this form.
> `5G NSA | B7 (2600 MHz) + B1 (2100 MHz) / n78 (3500 MHz)`

If I understand you correctly, in 5G NSA mode, do we need to separate the output of 4G and 5G cells in the MODE variable with `/`?

I've attached AT commands manual. It does not explain why there are two PCC lines in the GTCAINFO response.

[Fibocom_FM350_AT+Commands+User+Manual_V2.10.pdf](https://github.com/4IceG/luci-app-3ginfo-lite/files/15007670/Fibocom_FM350_AT%2BCommands%2BUser%2BManual_V2.10.pdf)

**Comment by prusa-dev** [comment]
Ok, I think I understand
I'll make like this https://github.com/4IceG/luci-app-3ginfo-lite/issues/55#issuecomment-1881645327

**Comment by prusa-dev** [comment]
Here is update.
### LTE mode
lte_a

### 5G NSA mode
5g_nsa

### 5G SA mode
5g_sa

**Comment by 4IceG** [comment]
Hi @prusa-dev 
I know I'm complaining, but I would improve LTE-A so that there would not be so many '+' signs. The '+' sign in 3ginfo-lite separates the main/primary band from the aggregation bands.

**Comment by prusa-dev** [comment]
Hi @4IceG 

Could you please write the correct version of what should be in the technology section in the screenshot above?

Right now it looks like this:

Technology: LTE-A | B20 (800 MHz) + B3 (1800 MHz) + B7 (2600 MHz) + B7 (2600 MHz) + B1 (2100 MHz)

Technology: 5G NSA | B3 (1800 MHz) + B1 (2100 MHz) / n79 (4700 MHz)

Technology: 5G SA | n41 (2500 MHz)

**Comment by 4IceG** [comment]
Hi @prusa-dev , 
Check if the aggregated LTE-A bands are shown ok after my changes.

**Comment by 4IceG** [comment]
I made a small correction removing the last space.

**Comment by prusa-dev** [comment]
Hi @4IceG 
Thank you, I'll test it on weekends

**Comment by prusa-dev** [comment]
Hi @4IceG 

I have checked, everything works perfectly.

Here is output:
- LTE-A | B20 (800 MHz) + B3 (1800 MHz) / B7 (2600 MHz) / B7 (2600 MHz) / B1 (2100 MHz)
- 5G NSA | B3 (1800 MHz) + B1 (2100 MHz) / B7 (2600 MHz) / n79 (4700 MHz)
- 5G SA | n41 (2500 MHz)

I made some correction to remove `/` and `+` at the end, if band is only one.

**Pull request merged**
